name: myapp
description: "Kill the boss project."
version: 1.0.42+2

environment:
#'>=3.4.0-282.3.beta <4.0.0'
  sdk:  ^3.6.0-216.1.beta
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  dart_random_choice: any
  google_fonts: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
flutter:
  uses-material-design: true
  assets:
    - assets/img/